### ISSUE TITLE
New Discord Update Bug.

### ISSUE THREAD

**Issue by A983Hub** [BetterDiscord/BetterDiscord#906]
**Describe the Bug**
So i was using Discord one time, and a Discord Update came! Cool, right? Well... turns out that it was crashing my Discord with BetterDiscord, and an error appeared that BetterDiscord crashed my client, and i had to do the ctrl + R technique. However, something was VERY OFF. (Context in the Screenshot). Can anybody help me get my BetterDiscord back please?

**To Reproduce**
1. Get the new Discord Update
2. BetterDiscord crashes the client.
3. You have to continue without BetterDiscord.
4. Ctrl + R, glitched UI, back to no BetterDiscord.

**Expected Behavior**
Recent Discord Update.

**Screenshots**
![bandicam 2021-07-15 14-08-47-398](https://user-images.githubusercontent.com/69992569/125851050-69a9f378-2cfe-4373-b73d-45f5047ec30c.jpg)

**Discord Version**
Stable

**Additional Context**
None.

**Comment by dav1312** [comment]
### Make sure to test this things without plugins or themes

**Comment by notLeM** [comment]
Remove `0PluginLibrary.plugin.js` and `0BDFDB.plugin.js` from your plugins folder, they're the plugins causing the crash (its possible more plugins are causing it but those are the two I had to remove)

**Comment by A983Hub** [comment]
> Remove `0PluginLibrary.plugin.js` and `0BDFDB.plugin.js` from your plugins folder, they're the plugins causing the crash (its possible more plugins are causing it but those are the two I had to remove)

I tested it and, it works now! A blessing from the lord! However, most of the plugins i used needed these libraries, so i had to go through like, 10+ Popups asking me to download the libraries (Even though they were the ones causing BetterDiscord to crash in the first place.)

**Comment by rauenzi** [comment]
Can you try re-adding `0PluginLibrary.plugin.js`? That one should be working

**Comment by A983Hub** [comment]
> Can you try re-adding `0PluginLibrary.plugin.js`? That one should be working

No... no i don't think so. I think that's the one that made BetterDiscord go haywire.

**Comment by rauenzi** [comment]
Have you grabbed the latest version? That one is working for me, the other is not.

**Comment by A983Hub** [comment]
> Have you grabbed the latest version? That one is working for me, the other is not.

I grabbed the latest version shown by the "Library Missing" Popup, and it still crashes my BetterDiscord.

**Comment by rauenzi** [comment]
That could have been either library... either way this is a dup of #904
